[
  {
    "enable": true,
    "alias": "刘展硕",
    "phone": "18537780158",
    "password": "2636226335wu",
    "deviceType": "Xiaomi|Mi 13Ultra|13",
    "deviceId": "f8269780ffae4a7aa9142acd1dd051641f2c",
    "address": "中国河南省新乡市长垣县魏庄工业区",
    "longitude": "116.397128",
    "latitude": "39.916527",
    "pushKey": "ec3fe310e5784cf0870ec3270d2cde12"
  }
]
